export default {
  products: [
    {
      _id: '1',
      name: 'Galaxy S24 Ultra',
      category: 'Phones',
      image: '/images/tmobile/galaxy-s24-ultra.png',
      price: 1299.99,
      brand: 'Samsung',
      rating: 4.8,
      numReviews: 214,
      countInStock: 12,
      description:
        '6.8" QHD+ display, 200MP camera and Galaxy AI on the T-Mobile 5G network.',
    },
    {
      _id: '2',
      name: 'iPhone 15 Pro Max',
      category: 'Phones',
      image: '/images/tmobile/iphone-15-pro-max.png',
      price: 1199.99,
      brand: 'Apple',
      rating: 4.9,
      numReviews: 342,
      countInStock: 10,
      description:
        'Titanium design, A17 Pro chip and 5x telephoto camera. 5G on T-Mobile.',
    },
    {
      _id: '3',
      name: 'iPhone 15',
      category: 'Phones',
      image: '/images/tmobile/iphone-15.png',
      price: 799.99,
      brand: 'Apple',
      rating: 4.7,
      numReviews: 188,
      countInStock: 15,
      description:
        'Dynamic Island, 48MP main camera and USB-C. On Us with eligible trade-in.',
    },
    {
      _id: '4',
      name: 'Galaxy S24',
      category: 'Phones',
      image: '/images/tmobile/galaxy-s24.png',
      price: 799.99,
      brand: 'Samsung',
      rating: 4.6,
      numReviews: 121,
      countInStock: 14,
      description:
        'Compact 6.2" flagship with Galaxy AI, all-day battery and 5G Ultra Capacity.',
    },
    {
      _id: '5',
      name: 'Pixel 8 Pro',
      category: 'Phones',
      image: '/images/tmobile/pixel-8-pro.png',
      price: 999.99,
      brand: 'Google',
      rating: 4.6,
      numReviews: 97,
      countInStock: 8,
      description:
        'Google Tensor G3, Super Actua display and 7 years of OS updates.',
    },
    {
      _id: '6',
      name: 'Pixel 8',
      category: 'Phones',
      image: '/images/tmobile/pixel-8.png',
      price: 699.99,
      brand: 'Google',
      rating: 4.5,
      numReviews: 76,
      countInStock: 11,
      description:
        'Best Take, Magic Editor and an all-day adaptive battery on T-Mobile 5G.',
    },
    {
      _id: '7',
      name: 'Galaxy A54 5G',
      category: 'Phones',
      image: '/images/tmobile/galaxy-a54.png',
      price: 449.99,
      brand: 'Samsung',
      rating: 4.4,
      numReviews: 64,
      countInStock: 20,
      description:
        'Big 6.4" display, 50MP camera and 5G speeds at a mid-range price.',
    },
    {
      _id: '8',
      name: 'Motorola edge (2025)',
      category: 'Phones',
      image: '/images/tmobile/motorola-edge.png',
      price: 599.99,
      brand: 'Motorola',
      rating: 4.3,
      numReviews: 41,
      countInStock: 9,
      description:
        'Endless edge display, 68W TurboPower charging and clean Android.',
    },
    {
      _id: '9',
      name: 'REVVL 8 Pro 5G',
      category: 'Phones',
      image: '/images/tmobile/revvl-8-pro.png',
      price: 199.99,
      brand: 'T-Mobile',
      rating: 4.1,
      numReviews: 53,
      countInStock: 25,
      description:
        'T-Mobile\u2019s own 5G phone: 6.8" display, 50MP camera and 5000mAh battery.',
    },
    {
      _id: '10',
      name: 'Galaxy Tab S9 FE 5G',
      category: 'Tablets',
      image: '/images/tmobile/galaxy-tab-s9.png',
      price: 649.99,
      brand: 'Samsung',
      rating: 4.5,
      numReviews: 37,
      countInStock: 7,
      description:
        '10.9" tablet with S Pen included and 5G, ready for a T-Mobile data plan.',
    },
    {
      _id: '11',
      name: 'Inseego MiFi PRO M4',
      category: 'Tablets',
      image: '/images/tmobile/inseego-hotspot.png',
      price: 349.99,
      brand: 'Inseego',
      rating: 4.2,
      numReviews: 28,
      countInStock: 13,
      description:
        'Share T-Mobile 5G with up to 30 devices. Perfect for travel and work sites.',
    },
    {
      _id: '12',
      name: 'Galaxy Watch8 44mm LTE',
      category: 'Watches',
      image: '/images/tmobile/galaxy-watch8.png',
      price: 329.99,
      brand: 'Samsung',
      rating: 4.5,
      numReviews: 59,
      countInStock: 10,
      description:
        'Stay connected without your phone using T-Mobile DIGITS on your wrist.',
    },
    {
      _id: '13',
      name: 'Apple Watch SE 3',
      category: 'Watches',
      image: '/images/tmobile/apple-watch-se.png',
      price: 279.99,
      brand: 'Apple',
      rating: 4.6,
      numReviews: 83,
      countInStock: 12,
      description:
        'Crash Detection, fitness tracking and cellular on the T-Mobile network.',
    },
    {
      _id: '14',
      name: 'Galaxy Buds2 Pro',
      category: 'Accessories',
      image: '/images/tmobile/galaxy-buds2-pro.png',
      price: 229.99,
      brand: 'Samsung',
      rating: 4.4,
      numReviews: 91,
      countInStock: 18,
      description:
        '24-bit Hi-Fi audio with intelligent active noise cancelling.',
    },
    {
      _id: '15',
      name: 'AirPods Pro (2nd gen)',
      category: 'Accessories',
      image: '/images/tmobile/airpods-pro.png',
      price: 249.99,
      brand: 'Apple',
      rating: 4.8,
      numReviews: 260,
      countInStock: 16,
      description:
        'Adaptive Audio, Personalized Spatial Audio and a USB-C charging case.',
    },
    {
      _id: '16',
      name: 'Beats Studio Pro',
      category: 'Accessories',
      image: '/images/tmobile/beats-studio-pro.png',
      price: 349.99,
      brand: 'Beats',
      rating: 4.3,
      numReviews: 47,
      countInStock: 6,
      description:
        'Over-ear noise cancelling headphones with up to 40 hours of listening.',
    },
    {
      _id: '17',
      name: '30W Fast Charger',
      category: 'Accessories',
      image: '/images/tmobile/fast-charger-30w.png',
      price: 29.99,
      brand: 'T-Mobile',
      rating: 4.2,
      numReviews: 112,
      countInStock: 40,
      description:
        'Compact USB-C wall charger that fast charges most phones and tablets.',
    },
    {
      _id: '18',
      name: '10,000 mAh Power Bank',
      category: 'Accessories',
      image: '/images/tmobile/power-bank-10k.png',
      price: 49.99,
      brand: 'T-Mobile',
      rating: 4.4,
      numReviews: 74,
      countInStock: 22,
      description:
        'Two full phone charges on the go, with USB-C PD in and out.',
    },
    {
      _id: '19',
      name: 'JBL Charge 5',
      category: 'Accessories',
      image: '/images/tmobile/jbl-charge-5.png',
      price: 179.99,
      brand: 'JBL',
      rating: 4.7,
      numReviews: 138,
      countInStock: 9,
      description:
        'Waterproof portable speaker with 20 hours of playtime and a built-in power bank.',
    },
    {
      _id: '20',
      name: 'OtterBox Defender Case',
      category: 'Accessories',
      image: '/images/tmobile/otterbox-case.png',
      price: 59.99,
      brand: 'OtterBox',
      rating: 4.5,
      numReviews: 205,
      countInStock: 30,
      description:
        'Multi-layer drop protection with a holster that doubles as a kickstand.',
    },
    {
      _id: '21',
      name: '6 ft USB-C Cable',
      category: 'Accessories',
      image: '/images/tmobile/usb-c-cable.png',
      price: 19.99,
      brand: 'T-Mobile',
      rating: 4.1,
      numReviews: 156,
      countInStock: 50,
      description:
        'Braided USB-C to USB-C cable rated for 60W charging and fast data.',
    },
    {
      _id: '22',
      name: 'Tempered Glass Protector',
      category: 'Accessories',
      image: '/images/tmobile/screen-protector.png',
      price: 24.99,
      brand: 'ZAGG',
      rating: 4.0,
      numReviews: 88,
      countInStock: 45,
      description:
        'Scratch resistant tempered glass with an easy alignment install tray.',
    },
  ],
};
